name: Deploy React UI

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Quantara.UI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: devops
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "Quantara.UI/dist/*"
          target: "/var/www/quantara-ui"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: devops
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo systemctl reload nginx